apiVersion: apps/v1
kind: Deployment
metadata:
  name: labarq-rag-depl
  labels:
    app: labarq-rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labarq-rag
  template:
    metadata:
      labels:
        app: labarq-rag
    spec:
      containers:
        - name: labarq-rag
          image: labarqragacr.azurecr.io/labarq-rag:__TAG__
          ports:
          - containerPort: 8000
          envFrom:
            - secretRef:
                name: postgres-rag-secret
            - configMapRef:
                name: postgres-rag-configmap
            - secretRef:
                name: labarq-rag-secret
---
apiVersion: v1
kind: Service
metadata:
  name: labarq-rag-serv
spec:
  selector:
    app: labarq-rag
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: labarq-rag-ingr
spec:
  rules:
    - host: rag.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: labarq-rag-serv
                port:
                  number: 80
