apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-rag-configmap
data:
  POSTGRES_USER: "rag"
  POSTGRES_DB: "rag"
  POSTGRES_URL: "postgres-rag-serv"
  POSTGRES_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-rag-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: rag
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-rag-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-rag-sset
spec:
  serviceName: postgres-rag
  replicas: 1
  selector:
    matchLabels:
      app: postgres-rag
  template:
    metadata:
      labels:
        app: postgres-rag
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:pg17
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-rag-secret
            - configMapRef:
                name: postgres-rag-configmap
          volumeMounts:
            - name: postgres-rag-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-rag-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-rag-serv
spec:
  selector:
    app: postgres-rag
  ports:
    - port: 5432
      targetPort: 5432
